### ISSUE TITLE
Discord logo image is broken by ad-blocker subscription 'Fanboy's Annoyance List'

### ISSUE THREAD

**Issue by ranolfi** [codidact/landing-page#12]
Commit b3246d37 places all third-party logo images under `/assets/img/3rd-party` and as a result the Discord logo no longer appears: 
![image](https://user-images.githubusercontent.com/8507649/70861036-bb8c7d00-1f07-11ea-8965-483b7a948223.png)

This is caused by uBlock origin with the Easylist's 'Fanboy's Annoyance List' subscription enabled.

Reported at https://github.com/easylist/easylist/issues/4525. Awaiting resolution.

[edit]: This was not evident when testing locally.

**Comment by luap42** [comment]
As this seems to be blocking deploy of the recent updates, it has been suggested by me (and @manassehkatz in Discourse) to simply rename the icon to something that is not blocked. The prior PR (#13) aims to do so.

**Comment by luap42** [comment]
This will be fixed either with #13 or when uBlock fixes their issue (whatever happens first). Closing as completed.

**Comment by ranolfi** [comment]
I'll leave it `status: blocked` for a while to make it easier to track the "proper solution". Merging PR now.

**Comment by ranolfi** [comment]
Fixed upstream. https://github.com/easylist/easylist/issues/4525
