### ISSUE TITLE
Mailing List

### ISSUE THREAD

**Issue by manassehkatz** [codidact/landing-page#19]
Added new mailing list (ezmlm, provided with the hosting account) announcements@codidact.org

1 - Add a short description and subscription link (mailto:announcements-subscribe@codidact.org) to the landing page.

2 - Not quite as easy: Add a small form that accepts an email address and sends a subscription message. The catch is that this (a) requires processing a form and (b) generating a specially crafted outbound email. The key is "To". For me@example.com, it should be To: announcements-subscribe-me=example.com@codidact.org See https://untroubled.org/ezmlm/manual/Subscribing.html for details.

The server has PHP on by default, and this is literally just a few lines of PHP, so it could all run on the same server. Except I'm not sure where the landing page is actually hosted any more. If it is on the original codidact.org/.com server @ 192.252.154.28 then PHP is available and an easy way to take care of this.

Form submission should check for a nominally valid email address (really just @ in the middle and at least one period in the right-side), send the message and display some notification (popup?) to the user - e.g., "Thank you for subscribing. Check your email for a confirmation and Reply to the email to complete the subscription process" (or similar) - and then redisplay the main landing page after "OK".

**Comment by ArtOfCode-** [comment]
_Teeechnically_ an email address without a period on the right hand side is also valid: `email@localhost` is valid, as is `admin@org` - though they don't tend to get used very much.

**Comment by mattjbrent** [comment]
@luap42 were you working on this form in PHP - where is this at?

**Comment by luap42** [comment]
> @luap42 were you working on this form in PHP - where is this at?
> &mdash;@mattjbrent 

Wait what? I was never working on that AFAICT. I think @Daksh14 (weegee) was working on that, but it was definitely not me.

**Comment by jflopezfernandez** [comment]
I can knock this out in a few minutes. @manassehkatz do you know what version of PHP the server is running? And can you install PEAR modules? If not I can just use the native PHP mail functionality, but it just isn't as flexible.

**Comment by mattjbrent** [comment]
Sorry @luap42 @Daksh14 can you confirm this? Just wanting to know where we are with this

**Comment by jflopezfernandez** [comment]
@mattjbrent I have a prototype ready to hook up to the mail server. Let me know if you guys need me, and I can set it up on the host

![Prototype Signup Form](https://imgur.com/HhMxGLL.png)

**Comment by ranolfi** [comment]
@jflopezfernandez PHP version 7.3.8. I've just set up a phpinfo file, DM me if you need further info so I can refer you to it. Would share here but not sure of the implications for the rest of the team.

**Comment by manassehkatz** [comment]
> I can knock this out in a few minutes. @manassehkatz do you know what version of PHP the server is running? And can you install PEAR modules? If not I can just use the native PHP mail functionality, but it just isn't as flexible.

PHP version already answered.

PEAR - a quick search and I didn't see any easy install. I can check on that, but probably easier, since this is an incredibly simple mail issue, to just use the native functions.

**Comment by mattjbrent** [comment]
@Daksh14 Have you made any movement with this - we could probably do with getting this done and dusted?

**Comment by Daksh14** [comment]
I'll set up the PHP page with the existing landing page.
