### ISSUE TITLE
Re-incorporate FAQ to the new homepage

### ISSUE THREAD

**Issue by ranolfi** [codidact/landing-page#32]
Merging #30 has effectively reverted commit 06f478c8, which added FAQ to the homepage.

To be re-implemented.

@codidact/frontend, anyone up to the task?

**Comment by ranolfi** [comment]
If anyone wants to see what the old version looked like, it's currently up at https://codidact.org/envs/06f478c8/.

The previous implementation, as you'll see, relies on a GitHub *gist* that lives under https://gist.github.com/ArtOfCode-/b6088cc5ad9c98d4dfa9f16e234a1f85 and is embedded in [javascript form](https://gist.github.com/ArtOfCode-/b6088cc5ad9c98d4dfa9f16e234a1f85.js).

While we're at it - can we come up with something that is as easy to manage, but resides under the [Codidact organization](https://github.com/codidact) - preferably, the [docs](https://github.com/codidact/docs/) repository? Bonus points if it doesn't require JavaScript to render. @ArtOfCode-, @mattjbrent - any suggestions?

**Comment by mattjbrent** [comment]
I'm hesitant to over complicate this. IMO i'd rather have this hosted in a docs repo and maintained there then just created as a separate page or a new section on the landing page statically using HTML.

We can just create a process where we create an issue in landing page any time the doc is updated.

**Comment by ranolfi** [comment]
That's good enough @mattjbrent. More or less what I had in mind, anyway.

Issue's up for grabs!

**Comment by cellio** [comment]
We need to edit that FAQ if we're bringing it back.  Since it was written, we decided to adopt QPixel as the platform (at least for a while), so the stuff about not running the platform yet and Writing being an anomaly needs to change.  We should have a FAQ, but not *this* FAQ.  Can the fix for this including finding a home for it in the repo so our docs team can propose edits?

**Comment by mattjbrent** [comment]
thanks for your input @galegosimpatico @cellio I vote to just close this ticket and open a new one for finding the FAQ home?

**Comment by cellio** [comment]
@mattjbrent also assess what should be in a FAQ.  So many FAQs out there do not seem to take the "F" and "A" parts seriously -- let's make sure we address questions people actually have, and that what we say is up to date.  (The old one, being old and early, talks about how we're unhappy with SE and thus set this up etc -- true, but not really our core identity *now*.)

**Comment by mattjbrent** [comment]
As per above comment closing this issue out.
