### ISSUE TITLE
Background SVG asset not loading when deployed to subdirectories due to leading slash in URI

### ISSUE THREAD

**Issue by ranolfi** [codidact/landing-page#33]
This one was actually brought up by @manassehkatz and we dismissed it at first, believing it to be due to GitHub Pages not rendering SVGs for security concerns, but that turned out to be incorrect.

Consider the staging deployment at https://codidact.github.io/landing-page/.

How it should look: 
![image](https://user-images.githubusercontent.com/8507649/73445570-bbbacd80-4339-11ea-82a6-4078590cf121.png)

How it looks: 
![image](https://user-images.githubusercontent.com/8507649/73445538-ab0a5780-4339-11ea-8150-663c5f1f9907.png)

The background SVG asset https://codidact.github.io/assets/img/hero-bg.svg does not load. Notice anything?

The zen among us will notice the missing subdirectory string (`landing-page/`) in the resource path.

The culprit is https://github.com/codidact/landing-page/blob/7c2670d836bfc06ff23a1076b9a3488f60f36117/src/styles/sections/hero.scss#L2.

Since the code is "compiled" to `url(/assets/img/hero-bg.svg)`<sup>1</sup>, one *possible* solution would be:

`url("../../assets/img/hero-bg.svg")`

...but I'm not sure how robust that is for every case.

<br>
-

<sub>1: shame how the style guidelines aren't kept after SCSS compilation (the double quotes) :|</sub>

**Comment by ranolfi** [comment]
I wasn't aware that relative `url()` paths in CSS are relative to the CSS asset itself and not to the document in which it is included<sup>[\[1\]](https://stackoverflow.com/a/940475/3258851)</sup>. As such, the straightforward solution - demonstrated in terms of processed ("compiled") CSS would actually be:

`url("../img/hero-bg.svg")`

However, it's been a little painful getting that to work on the SCSS / Webpack setup.

It seems this is [not an uncommon difficulty](https://www.google.com/search?q=Module+parse+failed%3A+Unexpected+token+svg). See also https://github.com/angular/angular-cli/issues/12797.

Couldn't sort this out!

I mean, I got it working by changing line 2 from the `hero.scss` file linked above to

`background-image: url("../../dist/assets/img/hero-bg.svg"), $color-gradient-alternate;`

and installing/setting up [svg-url-loader](https://www.npmjs.com/package/svg-url-loader), but this is not a proper solution as it encodes the svg to `data:image/svg+xml` and that's not what we would expect.

**Comment by Daksh14** [comment]
The deign is old and this is fixed, the added slash no more affects any assets
