### ISSUE TITLE
Incorporate more of the vision

### ISSUE THREAD

**Issue by cellio** [codidact/landing-page#34]
The landing page currently focuses on Q&A, which makes sense given how we got here, but we now have broad agreement on a [vision](https://forum.codidact.org/t/a-vision-for-codidact/830?u=cellio) that's broader.  Q&A is *central* but we're not *just* doing Q&A; communities need some other tools too.   Also, in the "communities first" section, I don't think "focusing around the answer" is quite right; we're focusing on empowering communities to learn and share together, which is mostly but not exclusively about answering questions.

Maybe even link to the full statement on our wiki?  https://github.com/codidact/docs/wiki/The-Codidact-Vision  (Use the wiki page not the forum post; I included the latter in the first paragraph to support my claim of broad support.)

**Comment by mattjbrent** [comment]
@cellio could you provide us with some more direction on what you want here - perhaps a reworded paragraph and whether you want the link as a button or just as a nested anchor tag like we do in other places - thanks

**Comment by cellio** [comment]
Will do after Shabbat.

**Comment by mattjbrent** [comment]
@cellio any chance we can get some movement on this - I think it's important enough to warrant change.

**Comment by cellio** [comment]
How do these changes look?

What is Codidact?  
Ever had a question? Ever had an answer? Ever had knowledge to share?  
We believe that coming together to inquire and learn, to share and teach each other, makes the world a better place.  We also believe that (... rest of paragraph)

--

Our goal is to build an open-source platform for community-driven Q&A sites. We aim to welcome beginners and experts alike and to empower communities of learners and teachers. We'll fund it by seeking donations, not by paywalls, and work with individual communities that want to join us.

--

Ultimately, we are all looking for answers to life's big - and little - questions. We want to build an amazing platform that makes it easier to ask questions and curate answers in a non-hostile environment, so you can get to the answers you need without the fuss.

**Comment by luap42** [comment]
This has been completed.
