### ISSUE TITLE
Add license coverage/exception notice for assets

### ISSUE THREAD

**Issue by ranolfi** [codidact/landing-page#36]
The software is currently licensed under the MIT License, but it seems artwork isn't (re: #35).

Add a notice to README specifying that the MIT License does not cover assets under https://github.com/codidact/landing-page/tree/master/dist/assets/img and particularly not those within the [3rd-party](https://github.com/codidact/landing-page/tree/master/dist/assets/img/3rd-party) directory.

Note - same goes for https://github.com/codidact/landing-page/tree/master/src/img.

**Comment by Daksh14** [comment]
Fixed by #54
