### ISSUE TITLE
App hints to report issue

### ISSUE THREAD

**Issue by galegosimpatico** [codidact/landing-page#51]
**Describe the bug**
App told me to report. line to blame is maybe https://github.com/codidact/landing-page/blame/master/dist/subscribe.php#L88.

**To Reproduce**
1. Go to 'landing page'.
2. Write your mail address.
3. Click on 'subscribe'.
4. See error.

**Expected behavior**
Sent me some email message instead of hinting me to report issue.

**Screenshots**
Not applicable.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Opera
 - Version: We don't really care for server errors.

**Comment by dagelf** [comment]
Still ongoing.

**Comment by galegosimpatico** [comment]
https://github.com/codidact/landing-page/issues/59#event-3836126942
