### ISSUE TITLE
Mail not sent when subscribing to mailing list

### ISSUE THREAD

**Issue by danzek** [codidact/landing-page#59]
**Describe the bug**
I attempted to join the mailing list. I received the error:

>Mail was not sent, please report the issue here

**To Reproduce**
1. Go to https://codidact.org/
2. Scroll to bottom and enter my email address
3. Click Subscribe button
4. Received above error message with link to report the issue here

**Expected behavior**
Being signed up for the mailing list.

**Smartphone (please complete the following information):**
 - Device: iPad mini (5th gen)
 - OS: iOS 13.7
 - Browser: FireFox for iOS
 - Version: 28.2 (2470)

**Additional context**
codidact.com appears to be down at the moment, so if the issue is related to the outage, feel free to close.

**Comment by manassehkatz** [comment]
I'm still investigating exactly what went wrong, but it should be working now.

**Comment by galegosimpatico** [comment]
Related to: https://github.com/codidact/landing-page/issues/44 https://github.com/codidact/landing-page/issues/51 https://github.com/codidact/landing-page/issues/58

Possible duplicates: https://github.com/codidact/landing-page/issues/51 https://github.com/codidact/landing-page/issues/58

**Comment by danzek** [comment]
It works now. Thanks.
