### ISSUE TITLE
Mention where repository of https://codidact.com/ exists

### ISSUE THREAD

**Issue by matkoniecz** [codidact/landing-page#82]
**Is your feature request related to a problem? Please describe.**
I wanted to open issue proposing change for https://codidact.com/contact (mention that Codidact is open source) and I am confused which repo is providing this page. In general codidact.com vs codidact.org is quite confusing

**Describe the solution you'd like**
Mention in readme of this repo where codidact.com code exists (it is also a landing page)

**Describe alternatives you've considered**
Merge codidact.org/codidact.com, mention on https://codidact.com/contact  that it is open source with a link to repo (in fact, that is what I wanted to propose)

**Additional context**
I am not 100% sure that https://codidact.com/ is open source as planned.

**Comment by Istiakshovon** [comment]
https://github.com/codidact/community-list/blob/master/contact.html

I have found the file. I am not going to say anything else...
