### ISSUE TITLE
Bad link to codidact.com in FAQ

### ISSUE THREAD

**Issue by cellio** [codidact/landing-page#87]
From email to support:

> At the FAQ's section on codidact.org, where it reads "What communities currently exist on Codidact?" the URL points to https://codidact.com./ which displays an error, one has to manually remove the period (.) before the slash.

I've verified the bug.  Was going to fix it (one-character change) but can't find the right place in this repo.

**Comment by Daksh14** [comment]
@cellio Next time just mention #87 or #issue-number to autoclose it once the PR gets merged
