### ISSUE TITLE
unable to subscribe

### ISSUE THREAD

**Issue by b-Istiak-s** [codidact/landing-page#88]
I was trying if I can subscribe, I had entered a valid email but I got the error

>Mail was not sent, please report the issue here

**Comment by cellio** [comment]
Reproduced.  High priority!

**Comment by cellio** [comment]
Fixed now.  For the record, here's the message from Discord:

> Fixed. I have to (one of these days) figure out/get the right code into the repo. The subscribe.php file needs a permanent fix - it had not changed this time, but been redeployed with the old broken one when other changes were deployed.
