### ISSUE TITLE
Broken image on landing page

### ISSUE THREAD

**Issue by cellio** [codidact/landing-page#92]
I'm not sure what's supposed to be here, but it's missing:

![Screen shot](https://user-images.githubusercontent.com/5557942/143524185-61f177da-42e9-40b8-9ad0-e05e67934847.png)

**Comment by cellio** [comment]
This is what I see in developer tools.  Note the "== $0" after this image link, but not the next one (which works).  I'm able to open the file just fine in GitHub.  I don't see anything obviously wonky in index.html.

![Screenshot, because I apparently can't cut/paste from this?](https://user-images.githubusercontent.com/5557942/143525639-5ad2cbe5-df31-4a1d-80fb-d2130db830dc.png)

**Comment by manassehkatz** [comment]
assets/img/3rd-party/searching.html file on production server was 0 length. Copied from repo to server.
